<?php
namespace Kunstmaan\AdminListBundle\Tests\AdminList\Configurator;

use Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 13:21:31.
 */
class AbstractAdminListConfiguratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractAdminListConfigurator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->object = new AbstractAdminListConfigurator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getAdminType
     * @todo   Implement testGetAdminType().
     */
    public function testGetAdminType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::setAdminType
     * @todo   Implement testSetAdminType().
     */
    public function testSetAdminType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::buildFilters
     * @todo   Implement testBuildFilters().
     */
    public function testBuildFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::buildActions
     * @todo   Implement testBuildActions().
     */
    public function testBuildActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::canEdit
     * @todo   Implement testCanEdit().
     */
    public function testCanEdit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::addField
     * @todo   Implement testAddField().
     */
    public function testAddField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::addExportField
     * @todo   Implement testAddExportField().
     */
    public function testAddExportField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::canDelete
     * @todo   Implement testCanDelete().
     */
    public function testCanDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::canAdd
     * @todo   Implement testCanAdd().
     */
    public function testCanAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::canExport
     * @todo   Implement testCanExport().
     */
    public function testCanExport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getExportUrlFor
     * @todo   Implement testGetExportUrlFor().
     */
    public function testGetExportUrlFor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getLimit
     * @todo   Implement testGetLimit().
     */
    public function testGetLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getSortFields
     * @todo   Implement testGetSortFields().
     */
    public function testGetSortFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getFields
     * @todo   Implement testGetFields().
     */
    public function testGetFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getExportFields
     * @todo   Implement testGetExportFields().
     */
    public function testGetExportFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::addSimpleAction
     * @todo   Implement testAddSimpleAction().
     */
    public function testAddSimpleAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::addItemAction
     * @todo   Implement testAddItemAction().
     */
    public function testAddItemAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::hasItemActions
     * @todo   Implement testHasItemActions().
     */
    public function testHasItemActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getItemActions
     * @todo   Implement testGetItemActions().
     */
    public function testGetItemActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::hasListActions
     * @todo   Implement testHasListActions().
     */
    public function testHasListActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getListActions
     * @todo   Implement testGetListActions().
     */
    public function testGetListActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getStringValue
     * @todo   Implement testGetStringValue().
     */
    public function testGetStringValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::addListAction
     * @todo   Implement testAddListAction().
     */
    public function testAddListAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getListTemplate
     * @todo   Implement testGetListTemplate().
     */
    public function testGetListTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::setListTemplate
     * @todo   Implement testSetListTemplate().
     */
    public function testSetListTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getAddTemplate
     * @todo   Implement testGetAddTemplate().
     */
    public function testGetAddTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::setAddTemplate
     * @todo   Implement testSetAddTemplate().
     */
    public function testSetAddTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getEditTemplate
     * @todo   Implement testGetEditTemplate().
     */
    public function testGetEditTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::setEditTemplate
     * @todo   Implement testSetEditTemplate().
     */
    public function testSetEditTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getDeleteTemplate
     * @todo   Implement testGetDeleteTemplate().
     */
    public function testGetDeleteTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::setDeleteTemplate
     * @todo   Implement testSetDeleteTemplate().
     */
    public function testSetDeleteTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::decorateNewEntity
     * @todo   Implement testDecorateNewEntity().
     */
    public function testDecorateNewEntity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getFilterBuilder
     * @todo   Implement testGetFilterBuilder().
     */
    public function testGetFilterBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::bindRequest
     * @todo   Implement testBindRequest().
     */
    public function testBindRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getPage
     * @todo   Implement testGetPage().
     */
    public function testGetPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getOrderBy
     * @todo   Implement testGetOrderBy().
     */
    public function testGetOrderBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Configurator\AbstractAdminListConfigurator::getOrderDirection
     * @todo   Implement testGetOrderDirection().
     */
    public function testGetOrderDirection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
