################ VARNISH ################
kunstmaancachebundle_varnish:
    resource: "@KunstmaanCacheBundle/Controller/VarnishController.php"
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%
