parameters:
    kunstmaan_cache.menu_adaptor.varnish.class: Kunstmaan\CacheBundle\Helper\Menu\VarnishMenuAdaptor
    kunstmaan_cache.helper.varnish.class: Kunstmaan\CacheBundle\Helper\VarnishHelper

services:
  Kunstmaan\CacheBundle\Helper\Menu\VarnishMenuAdaptor:
    tags:
      -  { name: "kunstmaan_admin.menu.adaptor" }

  Kunstmaan\CacheBundle\Helper\VarnishHelper:
    arguments:
      - "@fos_http_cache.cache_manager"
      - '@Kunstmaan\AdminBundle\Helper\DomainConfigurationInterface'

  Kunstmaan\CacheBundle\EventListener\VarnishListener:
    arguments:
        - '@Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface'
        - '@Symfony\Component\Routing\RouterInterface'
    tags:
        - { name: 'kernel.event_listener', event: 'kunstmaan_node.configureActionMenu', method: 'onActionMenuConfigure' }
