KunstmaanFormBundle_formsubmissions:
    resource: '@KunstmaanFormBundle/Controller/FormSubmissionsController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%/formsubmissions
