<?php
namespace Kunstmaan\GeneratorBundle\Tests\Command;

use Kunstmaan\GeneratorBundle\Command\GenerateAdminListCommand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-03 at 09:51:41.
 */
class GenerateAdminListCommandTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GenerateAdminListCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GenerateAdminListCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
