<?php
namespace Kunstmaan\GeneratorBundle\Tests\Command;

use Kunstmaan\GeneratorBundle\Command\GenerateDefaultSiteCommand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-03 at 09:51:41.
 */
class GenerateDefaultSiteCommandTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GenerateDefaultSiteCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GenerateDefaultSiteCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\GeneratorBundle\Command\GenerateDefaultSiteCommand::setSiteGenerator
     * @todo   Implement testSetSiteGenerator().
     */
    public function testSetSiteGenerator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
