<?php
namespace Kunstmaan\MediaBundle\Tests\Repository;

use Kunstmaan\MediaBundle\Repository\FolderRepository;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:32.
 */
class FolderRepositoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FolderRepository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FolderRepository;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Repository\FolderRepository::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Repository\FolderRepository::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Repository\FolderRepository::deleteFiles
     * @todo   Implement testDeleteFiles().
     */
    public function testDeleteFiles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Repository\FolderRepository::deleteChildren
     * @todo   Implement testDeleteChildren().
     */
    public function testDeleteChildren()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Repository\FolderRepository::getAllFolders
     * @todo   Implement testGetAllFolders().
     */
    public function testGetAllFolders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Repository\FolderRepository::getAllFoldersByType
     * @todo   Implement testGetAllFoldersByType().
     */
    public function testGetAllFoldersByType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Repository\FolderRepository::getFolder
     * @todo   Implement testGetFolder().
     */
    public function testGetFolder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
