services:
    Kunstmaan\ArticleBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\ArticleBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
