services:
    Kunstmaan\ArticleBundle\Twig\ArticleTwigExtension:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Symfony\Component\Routing\RouterInterface'
        tags:
            -  { name: twig.extension }
