parameters:

services:
    kunstmaan_articlebundle.twig.extension:
        class: 'Kunstmaan\ArticleBundle\Twig\ArticleTwigExtension'
        arguments: ['@doctrine.orm.entity_manager', '@router', '@request_stack']
        tags:
            -  { name: twig.extension }
