<?php
namespace Kunstmaan\MediaBundle\Tests\Entity;

use Kunstmaan\MediaBundle\Entity\ImageGallery;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:30.
 */
class ImageGalleryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ImageGallery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImageGallery;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\ImageGallery::getStrategy
     * @todo   Implement testGetStrategy().
     */
    public function testGetStrategy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
