<?php
namespace Kunstmaan\MediaBundle\Tests\Entity;

use Kunstmaan\MediaBundle\Entity\Image;

use Kunstmaan\MediaBundle\Entity\MediaContext;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:30.
 */
class MediaContextTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MediaContext
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MediaContext(Image::CONTEXT);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::setProvider
     * @todo   Implement testSetProvider().
     */
    public function testSetProvider()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::getProvider
     * @todo   Implement testGetProvider().
     */
    public function testGetProvider()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::addFormat
     * @todo   Implement testAddFormat().
     */
    public function testAddFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::hasFormat
     * @todo   Implement testHasFormat().
     */
    public function testHasFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::getFormat
     * @todo   Implement testGetFormat().
     */
    public function testGetFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::getFormats
     * @todo   Implement testGetFormats().
     */
    public function testGetFormats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::setMetadataClass
     * @todo   Implement testSetMetadataClass().
     */
    public function testSetMetadataClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\MediaContext::getMetadataClass
     * @todo   Implement testGetMetadataClass().
     */
    public function testGetMetadataClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
