<?php
namespace Kunstmaan\MediaPagePartBundle\Tests\Form;

use Kunstmaan\MediaPagePartBundle\Form\DownloadPagePartAdminType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-01 at 11:05:56.
 */
class DownloadPagePartAdminTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DownloadPagePartAdminType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DownloadPagePartAdminType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaPagePartBundle\Form\DownloadPagePartAdminType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaPagePartBundle\Form\DownloadPagePartAdminType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaPagePartBundle\Form\DownloadPagePartAdminType::setDefaultOptions
     * @todo   Implement testSetDefaultOptions().
     */
    public function testSetDefaultOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
