<?php
namespace Kunstmaan\PagePartBundle\Tests\Form;
use Kunstmaan\PagePartBundle\Form\TocPagePartAdminType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-20 at 12:29:42.
 */
class TocPagePartAdminTypeTest extends PagePartAdminTypeTestCase
{

    /**
     * @var TocPagePartAdminType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new TocPagePartAdminType();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert () == 'kunstmaan_pagepartbundle_tocpageparttype'.
     *
     * @covers                Kunstmaan\PagePartBundle\Form\TocPagePartAdminType::getName
     */
    public function testGetName()
    {
        $this->assertEquals('kunstmaan_pagepartbundle_tocpageparttype', $this->object->getName());
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Form\TocPagePartAdminType::buildForm
     */
    public function testBuildForm()
    {
        $this->object->buildForm($this->builder, array());
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Form\TocPagePartAdminType::setDefaultOptions
     */
    public function testSetDefaultOptions()
    {
        $this->object->setDefaultOptions($this->resolver);
        $resolve = $this->resolver->resolve();
        $this->assertEquals($resolve["data_class"], 'Kunstmaan\PagePartBundle\Entity\TocPagePart');
    }
}
