<?php

namespace Kunstmaan\AdminListBundle\Tests\Helper;

use Kunstmaan\AdminBundle\Helper\DomainConfiguration;
use PHPUnit_Framework_TestCase;
use Symfony\Component\DependencyInjection\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-19 at 09:56:53.
 */
class DomainConfigurationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DomainConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $c = new Container();
        $c->setParameter('multilanguage', true);
        $c->setParameter('defaultlocale', 'nl');
        $c->setParameter('requiredlocales', 'nl,fr');
        $this->object = new DomainConfiguration($c);
    }

    public function testGetSet()
    {
        $data = $this->object->getLocalesExtraData();
        $this->assertCount(0, $data);
        $data = $this->object->getFullHostConfig();
        $this->assertCount(0, $data);
        $this->assertNull($this->object->getFullHost());
        $this->assertNull($this->object->getFullHostById(123));
        $this->assertNull($this->object->getHostSwitched());
        $this->assertNull($this->object->getHostBaseUrl());
    }
}
