parameters:
    kunstmaan_admin.consoleexception.class: "Kunstmaan\AdminBundle\EventListener\ConsoleExceptionListener"


services:
    kunstmaan_admin.consolelogger.listener:
        class: %kunstmaan_admin.consoleexception.class%
        arguments:
            logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: console.exception }
