<?php
namespace Kunstmaan\MediaBundle\Tests\Helper;

use Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:31.
 */
class ImageGalleryStrategyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ImageGalleryStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImageGalleryStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getNewBulkUploadMediaInstance
     * @todo   Implement testGetNewBulkUploadMediaInstance().
     */
    public function testGetNewBulkUploadMediaInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getBulkUploadAccept
     * @todo   Implement testGetBulkUploadAccept().
     */
    public function testGetBulkUploadAccept()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getNewGallery
     * @todo   Implement testGetNewGallery().
     */
    public function testGetNewGallery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getGalleryClassName
     * @todo   Implement testGetGalleryClassName().
     */
    public function testGetGalleryClassName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getFormType
     * @todo   Implement testGetFormType().
     */
    public function testGetFormType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getFormHelper
     * @todo   Implement testGetFormHelper().
     */
    public function testGetFormHelper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\ImageGalleryStrategy::getListConfigurator
     * @todo   Implement testGetListConfigurator().
     */
    public function testGetListConfigurator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
