<?php
namespace Kunstmaan\MediaBundle\Tests\Helper;

use Kunstmaan\MediaBundle\Helper\MediaHelper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:31.
 */
class MediaHelperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MediaHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MediaHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\MediaHelper::getMedia
     * @todo   Implement testGetMedia().
     */
    public function testGetMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\MediaHelper::setMedia
     * @todo   Implement testSetMedia().
     */
    public function testSetMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\MediaHelper::getMediaFromUrl
     * @todo   Implement testGetMediaFromUrl().
     */
    public function testGetMediaFromUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\MediaHelper::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
