<?php

namespace Kunstmaan\AdminBundle\Tests\Entity;

use Codeception\Stub;
use Kunstmaan\AdminBundle\Entity\AbstractEntity;
use Kunstmaan\AdminBundle\Entity\AclChangeset;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-29 at 14:40:17.
 */
class AclChangesetTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AclChangeset
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AclChangeset();
    }

    public function test__construct()
    {
        $object = new AclChangeset();
        $this->assertEquals(AclChangeset::STATUS_NEW, $object->getStatus());
    }

    public function testSetAndGetChangeset()
    {
        $changeset = array('ROLE_ADMIN' => array('ADD' => array('VIEW', 'EDIT'), 'DEL' => 'PUBLISH'));
        $this->object->setChangeset($changeset);

        $this->assertEquals($changeset, $this->object->getChangeset());
    }

    public function testSetAndGetCreated()
    {
        $currentDate = new \DateTime('now');
        $this->object->setCreated($currentDate);

        $this->assertEquals($currentDate, $this->object->getCreated());
    }

    public function testSetAndGetLastModified()
    {
        $currentDate = new \DateTime('now');
        $this->object->setLastModified($currentDate);

        $this->assertEquals($currentDate, $this->object->getLastModified());
    }

    public function testSetAndGetRef()
    {
        /** @var AbstractEntity $entity */
        $entity = Stub::makeEmpty(AbstractEntity::class, ['getId' => 1, 'setId' => null, '__toString' => '1']);
        $this->object->setRef($entity);
        $this->assertEquals(1, $this->object->getRefId());
        $this->assertEquals(get_class($entity), $this->object->getRefEntityName());
    }

    public function testSetAndGetStatus()
    {
        $yesterday = new \DateTime('yesterday');
        $this->object->setLastModified($yesterday);

        $this->assertEquals(AclChangeset::STATUS_NEW, $this->object->getStatus());

        $this->object->setStatus(AclChangeset::STATUS_RUNNING);
        $this->assertNotEquals(AclChangeset::STATUS_NEW, $this->object->getStatus());
        $this->assertEquals(AclChangeset::STATUS_RUNNING, $this->object->getStatus());
        $this->assertNotEquals($yesterday, $this->object->getLastModified());
    }

    public function testSetAndGetPid()
    {
        $this->object->setPid(10);
        $this->assertEquals(10, $this->object->getPid());
    }

    public function testSetAndGetUser()
    {
        $user = new \Kunstmaan\AdminBundle\Entity\User();
        $this->object->setUser($user);

        $this->assertEquals($user, $this->object->getUser());
    }
}
