<?php

namespace Kunstmaan\ArticleBundle\Tests\Entity;

use DateTime;
use Kunstmaan\ArticleBundle\Entity\AbstractArticlePage;
use Kunstmaan\ArticleBundle\Form\AbstractArticlePageAdminType;
use PHPUnit_Framework_TestCase;

class ArticlePage extends AbstractArticlePage
{
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-04 at 16:54:04.
 */
class AbstractArticlePageTest extends PHPUnit_Framework_TestCase
{
    public function testGettersAndSetters()
    {
        $entity = new ArticlePage();
        $entity->setId(666);
        $entity->setDate(new DateTime());
        $entity->setTitle('NASA');
        $entity->setPageTitle('To infinty and beyond');
        $entity->setSummary('blah');

        $this->assertEquals(666, $entity->getId());
        $this->assertEquals('blah', $entity->getSummary());
        $this->assertEquals('To infinty and beyond', $entity->getPageTitle());
        $this->assertEquals('NASA', $entity->getTitle());
        $this->assertInstanceOf(DateTime::class, $entity->getDate());
        $this->assertEquals(AbstractArticlePageAdminType::class, $entity->getAdminType());
        $this->assertTrue(is_array($entity->getPossibleChildTypes()));
        $this->assertTrue(is_array($entity->getPagePartAdminConfigurations()));
    }
}
