preset: symfony
risky: false

disabled:
    - yoda_style
    - concat_without_spaces
    - phpdoc_summary
    - no_superfluous_phpdoc_tags_symfony
    - short_array_syntax

finder:
    exclude:
        - 'src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle'
    not-path:
        - "Tests/_support"
        - "TranslatorBundle/Tests/app2"
        - "TranslatorBundle/Tests/app"
        - "vendor_bower"
