<?php
namespace Kunstmaan\MediaBundle\Tests\Helper\File;

use Kunstmaan\MediaBundle\Entity\Media;

use Kunstmaan\MediaBundle\Helper\File\FileHelper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-28 at 14:19:21.
 */
class FileHelperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Media
     */
    protected $media;

    /**
     * @var FileHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->media = new Media();
        $this->object = new FileHelper($this->media);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\File\FileHelper::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\File\FileHelper::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\File\FileHelper::getFile
     * @todo   Implement testGetFile().
     */
    public function testGetFile()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\File\FileHelper::setFile
     * @todo   Implement testSetFile().
     */
    public function testSetFile()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\File\FileHelper::getMedia
     * @todo   Implement testGetMedia().
     */
    public function testGetMedia()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\File\FileHelper::getMediaFromUrl
     * @todo   Implement testGetMediaFromUrl().
     */
    public function testGetMediaFromUrl()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\File\FileHelper::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
