<?php
namespace Kunstmaan\MediaBundle\Tests\Form\File;

use Kunstmaan\MediaBundle\Form\File\FileType;
use Kunstmaan\MediaBundle\Tests\Form\AbstractTypeTest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-28 at 14:19:21.
 */
class FileTypeTest extends AbstractTypeTest
{
    /**
     * @var FileType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {$this->object = new FileType;
    }

    /**
     * @covers Kunstmaan\MediaBundle\Form\File\FileType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Form\File\FileType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Kunstmaan\MediaBundle\Form\File\FileType::setDefaultOptions
     * @todo   Implement testSetDefaultOptions().
     */
    public function testSetDefaultOptions()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
