parameters:
#    kuma_bundles_website.example.class: kumaBundles\WebsiteBundle\Example

services:
#    kuma_bundles_website.example:
#        class: %kuma_bundles_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
