services:
    Kunstmaan\UserManagementBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\UserManagementBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
