<?php
namespace Kunstmaan\MediaBundle\Tests\Event;

use Kunstmaan\MediaBundle\Entity\Image;

use Kunstmaan\MediaBundle\Event\MediaEvent;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:30.
 */
class MediaEventTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MediaEvent
     */
    protected $object;

    /**
     * @var Media
     */
    protected $media;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->media = new Image();
        $this->object = new MediaEvent($this->media);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Event\MediaEvent::setMedia
     * @todo   Implement testSetMedia().
     */
    public function testSetMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Event\MediaEvent::getMedia
     * @todo   Implement testGetMedia().
     */
    public function testGetMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Event\MediaEvent::setMetadata
     * @todo   Implement testSetMetadata().
     */
    public function testSetMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Event\MediaEvent::getMetadata
     * @todo   Implement testGetMetadata().
     */
    public function testGetMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
