services:
    Kunstmaan\SitemapBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\SitemapBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
