<?php

namespace Kunstmaan\RedirectBundle\Tests\Form;

use Kunstmaan\RedirectBundle\Form\RedirectAdminType;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-16 at 17:32:30.
 */
class RedirectAdminTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RedirectAdminType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RedirectAdminType();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\RedirectBundle\Form\RedirectAdminType::buildForm
     */
    public function testBuildForm()
    {
        $builder = $this->getMock('Symfony\Component\Form\Test\FormBuilderInterface');
        $builder
            ->expects($this->at(0))
            ->method('add')
            ->with('origin');
        $builder
            ->expects($this->at(1))
            ->method('add')
            ->with('target');
        $builder
            ->expects($this->at(2))
            ->method('add')
            ->with('permanent');

        $this->object->buildForm($builder, array());
    }

    /**
     * @covers Kunstmaan\RedirectBundle\Form\RedirectAdminType::getName
     */
    public function testGetName()
    {
        $this->assertEquals('redirect_form', $this->object->getName());
    }
}
