name: "~~~ENTITY~~~"
context: "main"
types:
    - { name: "Single Line text input", class: "Kunstmaan\\FormBundle\\Entity\\PageParts\\SingleLineTextPagePart" }
    - { name: "Multi Line text input", class: "Kunstmaan\\FormBundle\\Entity\\PageParts\\MultiLineTextPagePart" }
    - { name: "Email input", class: "Kunstmaan\\FormBundle\\Entity\\PageParts\\EmailPagePart" }
    - { name: "File upload", class: "Kunstmaan\\FormBundle\\Entity\\PageParts\\FileUploadPagePart" }
    - { name: "Choice input", class: "Kunstmaan\\FormBundle\\Entity\\PageParts\\ChoicePagePart" }
    - { name: "Submit button", class: "Kunstmaan\\FormBundle\\Entity\\PageParts\\SubmitButtonPagePart" }
    - { name: "Header", class: "Kunstmaan\\PagePartBundle\\Entity\\HeaderPagePart" }
    - { name: "Text", class: "Kunstmaan\\PagePartBundle\\Entity\\TextPagePart" }
    - { name: "Line", class: "Kunstmaan\\PagePartBundle\\Entity\\LinePagePart" }
    - { name: "TOC", class: "Kunstmaan\\PagePartBundle\\Entity\\TocPagePart" }
    - { name: "Link", class: "Kunstmaan\\PagePartBundle\\Entity\\LinkPagePart" }
    - { name: "To Top", class: "Kunstmaan\\PagePartBundle\\Entity\\ToTopPagePart" }
    - { name: "Image", class: "Kunstmaan\\MediaPagePartBundle\\Entity\\ImagePagePart" }
    - { name: "Download", class: "Kunstmaan\\MediaPagePartBundle\\Entity\\DownloadPagePart" }
    - { name: "Video", class: "Kunstmaan\\MediaPagePartBundle\\Entity\\VideoPagePart" }
    - { name: "Audio", class: "Kunstmaan\\MediaPagePartBundle\\Entity\\AudioPagePart" }
