<?php

namespace Kunstmaan\ConfigBundle\Tests\Entity;

use Kunstmaan\DashboardBundle\Entity\AnalyticsSegment;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-04 at 16:54:04.
 */
class AnalyticsSegmentTest extends PHPUnit_Framework_TestCase
{
    public function testGettersAndSetters()
    {
        $entity = new AnalyticsSegment();
        $entity->setName('Donald Trump');
        $entity->setQuery('query');
        $entity->setConfig(5);
        $entity->setoverviews([]);

        $this->assertEquals('Donald Trump', $entity->getName());
        $this->assertEquals('query', $entity->getQuery());
        $this->assertEquals(5, $entity->getConfig());
        $this->assertTrue(is_array($entity->getoverviews()));
    }
}
