services:
    Kunstmaan\SeoBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\SeoBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
