<?php

namespace Kunstmaan\FormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormSubmissionRepository extends EntityRepository
{

}