services:
    Kunstmaan\MultiDomainBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\MultiDomainBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
