kunstmaanmultidomainbundle_site_switch:
    resource: '@KunstmaanMultiDomainBundle/Controller/SiteSwitchController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%/multi-domain
