<?php

namespace Tests\Kunstmaan\FormBundle\Entity;

use Kunstmaan\FormBundle\Form\BooleanFormSubmissionType;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\FormFactory;
use Symfony\Component\Form\FormRegistry;
use Symfony\Component\Form\ResolvedFormTypeFactory;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-20 at 15:14:43.
 */
class BooleanFormSubmissionTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BooleanFormSubmissionType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BooleanFormSubmissionType();
    }

    public function testGetBlockPrefix()
    {
        $this->assertEquals('kunstmaan_formbundle_booleanformsubmissiontype', $this->object->getBlockPrefix());
    }

    public function testConfigureOptions()
    {
        $resolver = new OptionsResolver();
        $this->object->configureOptions($resolver);
        $dataClass = $resolver->offsetGet('data_class');
        $this->assertEquals('Kunstmaan\FormBundle\Entity\FormSubmissionFieldTypes\BooleanFormSubmissionField', $dataClass);
    }

    public function testBuildForm()
    {
        $registry = new FormRegistry([], new ResolvedFormTypeFactory());
        $factory = new FormFactory($registry);
        $dispatcher = new EventDispatcher();
        $builder = new FormBuilder('name', 'Kunstmaan\FormBundle\Entity\FormSubmissionFieldTypes\BooleanFormSubmissionField', $dispatcher, $factory);
        $builder->setCompound(true);
        $this->object->buildForm($builder, []);

        $form = $builder->getForm();
        $this->assertCount(1, $form->count());
    }

}
