<?php

namespace Kunstmaan\AdminListBundle\Tests\AdminList\FilterType\DBAL;

use Doctrine\DBAL\Query\QueryBuilder;
use Kunstmaan\AdminListBundle\AdminList\FilterType\DBAL\AbstractDBALFilterType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 13:21:33.
 */
class AbstractDBALFilterTypeTest extends \PHPUnit_Framework_TestCase
{
    public function testSetQueryBuilder()
    {
        /* @var AbstractDBALFilterType $object */
        $object = $this->getMockForAbstractClass('Kunstmaan\AdminListBundle\AdminList\FilterType\DBAL\AbstractDBALFilterType', array('column', 'alias'));

        /* @var QueryBuilder $queryBuilder */
        $queryBuilder = $this->getMockBuilder('Doctrine\DBAL\Query\QueryBuilder')
            ->disableOriginalConstructor()
            ->getMock();

        $object->setQueryBuilder($queryBuilder);
    }
}
