parameters:
    kunstmaan_pagepart.page_part_configuration_reader.class: Kunstmaan\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationReader
    kunstmaan_pagepart.page_part_configuration_parser.class: Kunstmaan\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationParser

    kunstmaan_pagepart.page_template_configuration_reader.class: Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationReader
    kunstmaan_pagepart.page_template_configuration_parser.class: Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationParser

    kunstmaan_page_part.page_template.page_template_configuration_service.class: Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationService
    kunstmaan_page_part.admin_factory.class: Kunstmaan\PagePartBundle\PagePartAdmin\PagePartAdminFactory

services:
    Kunstmaan\PagePartBundle\PagePartAdmin\Builder: ~

    Kunstmaan\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationReader:
        arguments:
          - '@Kunstmaan\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationParser'

    Kunstmaan\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationParser:
        public: false
        arguments:
          - '@kernel'
          - '%kunstmaan_page_part.page_parts_presets%'

    Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationReader:
        arguments:
          - '@Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationParser'

    Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationParser:
        public: false
        arguments:
          - '@kernel'
          - '%kunstmaan_page_part.page_templates_presets%'

    Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationService:
        arguments:
          - '@Kunstmaan\PagePartBundle\Repository\PageTemplateConfigurationRepository'
          - '@Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationReader'

    Kunstmaan\PagePartBundle\Repository\PageTemplateConfigurationRepository:
        public: false
        factory: [ '@Doctrine\ORM\EntityManagerInterface', 'getRepository' ]
        arguments:
          - 'KunstmaanPagePartBundle:PageTemplateConfiguration'

    Kunstmaan\PagePartBundle\PagePartAdmin\PagePartAdminFactory:
        arguments:
          - '@Symfony\Component\DependencyInjection\ContainerInterface'

    Kunstmaan\PagePartBundle\Twig\Extension\PagePartAdminTwigExtension:
        tags:
            -  { name: twig.extension }
        calls:
            - [ setUsesExtendedPagePartChooser, [ '%kunstmaan_page_part.extended%' ] ]

    Kunstmaan\PagePartBundle\Twig\Extension\PagePartTwigExtension:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
        tags:
            - { name: twig.extension }

    Kunstmaan\PagePartBundle\Twig\Extension\PageTemplateTwigExtension:
        arguments:
            - '@Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationService'
        tags:
            - { name: twig.extension }

    Kunstmaan\PagePartBundle\Helper\Services\PagePartCreatorService:
        calls:
            - [ setEntityManager, [ '@Doctrine\ORM\EntityManagerInterface' ] ]

    Kunstmaan\PagePartBundle\EventListener\NodeListener:
        arguments:
          - '@Doctrine\ORM\EntityManagerInterface'
          - '@Kunstmaan\PagePartBundle\PagePartAdmin\PagePartAdminFactory'
          - '@Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationReader'
          - '@Kunstmaan\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationReader'
          - '@Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationService'
        tags:
            - { name: kernel.event_listener, event: kunstmaan_node.adaptForm, method: adaptForm }

    Kunstmaan\PagePartBundle\EventListener\CloneListener:
        arguments:
          - '@Doctrine\ORM\EntityManagerInterface'
          - '@Kunstmaan\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationReader'
          - '@Kunstmaan\PagePartBundle\PageTemplate\PageTemplateConfigurationService'

        tags:
            - { name: kernel.event_listener, event: kunstmaan_admin.postDeepCloneAndSave, method: postDeepCloneAndSave }
