<?php
namespace Kunstmaan\MediaBundle\Tests\Helper\Cdn;

use Kunstmaan\MediaBundle\Helper\Cdn\RemoteServerCdn;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:30.
 */
class RemoteServerCdnTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RemoteServerCdn
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RemoteServerCdn;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Cdn\RemoteServerCdn::getFullPath
     * @todo   Implement testGetFullPath().
     */
    public function testGetFullPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Cdn\RemoteServerCdn::flush
     * @todo   Implement testFlush().
     */
    public function testFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
