KunstmaanRedirectBundle_redirect_adminlist:
    resource: '@KunstmaanRedirectBundle/Controller/RedirectAdminListController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%/settings/redirect/
