<?php
namespace Kunstmaan\AdminListBundle\Tests\AdminList\Filters\ORM;

use Kunstmaan\AdminListBundle\AdminList\Filters\ORM\BooleanFilter;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 13:21:34.
 */
class BooleanFilterTest extends ORMFilterTestCase
{
    /**
     * @var BooleanFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BooleanFilter('boolean', 'b');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Filters\ORM\BooleanFilter::bindRequest
     */
    public function testBindRequest()
    {
        $request = new Request(array('filter_value_boolean' => 'true'));

        $data = array();
        $uniqueId = 'boolean';
        $this->object->bindRequest($request, $data, $uniqueId);

        $this->assertEquals(array('value' => 'true'), $data);
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Filters\ORM\BooleanFilter::apply
     */
    public function testApply()
    {
        $qb = $this->getQueryBuilder();
        $qb->select('b')
            ->from('Entity', 'b');
        $this->object->setQueryBuilder($qb);
        $this->object->apply(array('value' => 'true'), 'boolean');

        $this->assertEquals('SELECT b FROM Entity b WHERE b.boolean = true', $qb->getDQL());
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Filters\ORM\BooleanFilter::getTemplate
     */
    public function testGetTemplate()
    {
        $this->assertEquals('KunstmaanAdminListBundle:Filters:booleanFilter.html.twig', $this->object->getTemplate());
    }
}
