<?php
namespace Kunstmaan\AdminListBundle\Tests\AdminList\Filters\ORM;

use Kunstmaan\AdminListBundle\AdminList\Filters\ORM\NumberFilter;
use Symfony\Component\HttpFoundation\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 13:21:34.
 */
class NumberFilterTest extends ORMFilterTestCase
{
    /**
     * @var NumberFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NumberFilter('number', 'b');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Filters\ORM\NumberFilter::bindRequest
     */
    public function testBindRequest()
    {
        $request = new Request(array('filter_comparator_number' => 'eq', 'filter_value_number' => 10));

        $data = array();
        $uniqueId = 'number';
        $this->object->bindRequest($request, $data, $uniqueId);

        $this->assertEquals(array('comparator' => 'eq', 'value' => 10), $data);
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Filters\ORM\NumberFilter::apply
     * @dataProvider applyDataProvider
     */
    public function testApply($comparator, $whereClause, $value, $testValue)
    {
        $qb = $this->getQueryBuilder();
        $qb->select('b')
            ->from('Entity', 'b');
        $this->object->setQueryBuilder($qb);
        $this->object->apply(array('comparator' => $comparator, 'value' => $value), 'number');

        $this->assertEquals("SELECT b FROM Entity b WHERE b.number $whereClause", $qb->getDQL());
        if ($testValue) {
            $this->assertEquals($value, $qb->getParameter('var_number')->getValue());
        }
    }

    public static function applyDataProvider()
    {
        return array(
            array('eq', '= :var_number', 1, true),
            array('neq', '<> :var_number', 2, true),
            array('lt', '< :var_number', 3, true),
            array('lte', '<= :var_number', 4, true),
            array('gt', '> :var_number', 5, true),
            array('gte', '>= :var_number', 6, true),
            array('isnull', 'IS NULL', 0, false),
            array('isnotnull', 'IS NOT NULL', 0, false),
        );
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Filters\ORM\NumberFilter::getTemplate
     */
    public function testGetTemplate()
    {
        $this->assertEquals('KunstmaanAdminListBundle:Filters:numberFilter.html.twig', $this->object->getTemplate());
    }
}
