ar: { analyzer: 'arabic' }
hy: { analyzer: 'armenian' }
eu: { analyzer: 'basque' }
bg: { analyzer: 'bulgarian' }
ca: { analyzer: 'catalan' }
zh: { analyzer: 'chinese' }
cs: { analyzer: 'czech' }
da: { analyzer: 'danish' }
nl: { analyzer: 'dutch' }
en: { analyzer: 'english' }
fi: { analyzer: 'finnish' }
fr: { analyzer: 'french' }
gl: { analyzer: 'galician' }
de: { analyzer: 'german' }
el: { analyzer: 'greek' }
hi: { analyzer: 'hindi' }
hu: { analyzer: 'hungarian' }
id: { analyzer: 'indonesian' }
it: { analyzer: 'italian' }
no: { analyzer: 'norwegian' }
fa: { analyzer: 'persian' }
pt: { analyzer: 'portuguese' }
ro: { analyzer: 'romanian' }
ru: { analyzer: 'russian' }
es: { analyzer: 'spanish' }
sv: { analyzer: 'swedish' }
se: { analyzer: 'swedish' }
ee: { analyzer: 'estonian' }
tr: { analyzer: 'turkish' }
th: { analyzer: 'thai' }
