<?php
namespace Kunstmaan\MediaBundle\Tests\Controller;

use Kunstmaan\MediaBundle\Controller\ChooserController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:29.
 */
class ChooserControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ChooserController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ChooserController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::ckeditorAction
     * @todo   Implement testCkeditorAction().
     */
    public function testCkeditorAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::ckeditorShowFolderAction
     * @todo   Implement testCkeditorShowFolderAction().
     */
    public function testCkeditorShowFolderAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::imageChooserAction
     * @todo   Implement testImageChooserAction().
     */
    public function testImageChooserAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::fileChooserAction
     * @todo   Implement testFileChooserAction().
     */
    public function testFileChooserAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::slideChooserAction
     * @todo   Implement testSlideChooserAction().
     */
    public function testSlideChooserAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::videoChooserAction
     * @todo   Implement testVideoChooserAction().
     */
    public function testVideoChooserAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::fileChooserShowFolderAction
     * @todo   Implement testFileChooserShowFolderAction().
     */
    public function testFileChooserShowFolderAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::imageChooserShowFolderAction
     * @todo   Implement testImageChooserShowFolderAction().
     */
    public function testImageChooserShowFolderAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::slideChooserShowFolderAction
     * @todo   Implement testSlideChooserShowFolderAction().
     */
    public function testSlideChooserShowFolderAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\ChooserController::videoChooserShowFolderAction
     * @todo   Implement testVideoChooserShowFolderAction().
     */
    public function testVideoChooserShowFolderAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
