<?php
namespace Kunstmaan\MediaBundle\Tests\Controller;

use Kunstmaan\MediaBundle\Controller\MediaController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:29.
 */
class MediaControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MediaController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MediaController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\MediaController::showAction
     * @todo   Implement testShowAction().
     */
    public function testShowAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\MediaController::deleteAction
     * @todo   Implement testDeleteAction().
     */
    public function testDeleteAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\MediaController::bulkUploadAction
     * @todo   Implement testBulkUploadAction().
     */
    public function testBulkUploadAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\MediaController::fileCreateAction
     * @todo   Implement testFileCreateAction().
     */
    public function testFileCreateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\MediaController::imageCreateAction
     * @todo   Implement testImageCreateAction().
     */
    public function testImageCreateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\MediaController::videoCreateAction
     * @todo   Implement testVideoCreateAction().
     */
    public function testVideoCreateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Controller\MediaController::slideCreateAction
     * @todo   Implement testSlideCreateAction().
     */
    public function testSlideCreateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
