services:
    kunstmaan_rest_core.service.data_transformer:
        class: Kunstmaan\Rest\CoreBundle\Service\DataTransformerService

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false
