<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcomtmh\appPhpunitDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcomtmh/appPhpunitDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBcomtmh.legacy');

    return;
}

if (!\class_exists(appPhpunitDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBcomtmh\appPhpunitDebugProjectContainer::class, appPhpunitDebugProjectContainer::class, false);
}

return new \ContainerBcomtmh\appPhpunitDebugProjectContainer();
