<?php
namespace Kunstmaan\MediaBundle\Tests\Form;

use Kunstmaan\MediaBundle\Form\MediaType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:30.
 */
class MediaTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MediaType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MediaType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Form\MediaType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Form\MediaType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Form\MediaType::setDefaultOptions
     * @todo   Implement testSetDefaultOptions().
     */
    public function testSetDefaultOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
