<?php
namespace Kunstmaan\AdminListBundle\Tests\AdminList\Actions;

use Kunstmaan\AdminListBundle\AdminList\Actions\SimpleAction;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 13:21:34.
 */
class SimpleActionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\AdminListBundle\AdminList\Actions\SimpleAction::__construct
     * @covers Kunstmaan\AdminListBundle\AdminList\Actions\SimpleAction::getUrl
     * @covers Kunstmaan\AdminListBundle\AdminList\Actions\SimpleAction::getIcon
     * @covers Kunstmaan\AdminListBundle\AdminList\Actions\SimpleAction::getLabel
     * @covers Kunstmaan\AdminListBundle\AdminList\Actions\SimpleAction::getTemplate
     */
    public function test__construct()
    {
        $object = new SimpleAction('http://www.domain.com/action', 'icon.png', 'Label', 'template.html.twig');

        $this->assertEquals('http://www.domain.com/action', $object->getUrl());
        $this->assertEquals('icon.png', $object->getIcon());
        $this->assertEquals('Label', $object->getLabel());
        $this->assertEquals('template.html.twig', $object->getTemplate());
    }
}
