<?php

namespace Kunstmaan\PagePartBundle\Tests\Entity;

use Kunstmaan\PagePartBundle\Entity\LinkPagePart;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-31 at 08:57:51.
 */
class LinkPagePartTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LinkPagePart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LinkPagePart();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::setUrl
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::getUrl
     */
    public function testSetGetUrl()
    {
        $this->object->setUrl('http://www.kunstmaan.be');
        $this->assertEquals('http://www.kunstmaan.be', $this->object->getUrl());
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::getOpenInNewWindow
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::setOpenInNewWindow
     */
    public function testGetSetOpenInNewWindow()
    {
        $this->object->setOpenInNewWindow(false);
        $this->assertFalse($this->object->getOpenInNewWindow());

        $this->object->setOpenInNewWindow(true);
        $this->assertTrue($this->object->getOpenInNewWindow());
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::setText
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::getText
     */
    public function testSetGetText()
    {
        $this->object->setText('Some dummy text');
        $this->assertEquals('Some dummy text', $this->object->getText());
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::__toString
     */
    public function testToString()
    {
        $this->assertEquals('LinkPagePart', $this->object->__toString());
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::getDefaultView
     */
    public function testGetDefaultView()
    {
        $this->assertEquals('KunstmaanPagePartBundle:LinkPagePart:view.html.twig', $this->object->getDefaultView());
    }

    /**
     * @covers Kunstmaan\PagePartBundle\Entity\LinkPagePart::getDefaultAdminType
     */
    public function testGetDefaultAdminType()
    {
        $this->assertInstanceOf('Kunstmaan\PagePartBundle\Form\LinkPagePartAdminType', $this->object->getDefaultAdminType());
    }
}
