
{{ bundle.getName()|lower }}_{{ entity_class|lower }}{{ type|lower }}_admin_list:
    resource: '@{{ bundle.getName() }}/Controller/{{ entity_class }}{{ type }}AdminListController.php'
    type:     annotation
    prefix:   /{_locale}/%kunstmaan_admin.admin_prefix%/{{ entity_class|lower }}{{ type|lower }}/
    requirements:
         _locale: "%requiredlocales%"
