
    {{ bundle.getName()|lower }}.{{ entity_class|lower }}.menu.adaptor:
        class: {{ namespace }}\Helper\Menu\{{ entity_class }}MenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }
