<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'kunstmaan_translator.menu.adaptor' shared service.

return $this->services['kunstmaan_translator.menu.adaptor'] = new \Kunstmaan\TranslatorBundle\Service\Menu\TranslatorMenuAdaptor();
