<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.profile' shared service.

return $this->services['twig.profile'] = new \Twig\Profiler\Profile();
