<?php

namespace Kunstmaan\MediaPagePartBundle\Tests\Entity;

use Kunstmaan\MediaBundle\Entity\Media;
use Kunstmaan\MediaPagePartBundle\Entity\SlidePagePart;
use Kunstmaan\MediaPagePartBundle\Form\SlidePagePartAdminType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-01 at 11:05:56.
 */
class SlidePagePartTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SlidePagePart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SlidePagePart();
    }

    public function testSetGetMedia()
    {
        $media = new Media();
        $media->setId(5);
        $this->object->setMedia($media);
        $this->assertEquals(5, $this->object->getMedia()->getId());
    }

    public function testGetDefaultView()
    {
        $defaultView = $this->object->getDefaultView();
        $this->assertEquals('KunstmaanMediaPagePartBundle:SlidePagePart:view.html.twig', $defaultView);
    }

    public function testGetDefaultAdminType()
    {
        $this->assertEquals(SlidePagePartAdminType::class, $this->object->getDefaultAdminType());
    }

    public function testToString()
    {
        $this->assertEmpty($this->object->__toString());
        $media = new Media();
        $media->setUrl('https://nasa.gov/spongebob.jpg');
        $this->object->setMedia($media);
        $this->assertEquals('https://nasa.gov/spongebob.jpg', $this->object->__toString());
    }
}
