<?php
namespace Kunstmaan\MediaBundle\Tests\Helper\Provider;

use Kunstmaan\MediaBundle\Helper\Provider\AbstractVideoProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:31.
 */
class AbstractVideoProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractVideoProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('Kunstmaan\MediaBundle\Helper\Provider\AbstractVideoProvider');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\AbstractVideoProvider::prepareMedia
     * @todo   Implement testPrepareMedia().
     */
    public function testPrepareMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\AbstractVideoProvider::saveMedia
     * @todo   Implement testSaveMedia().
     */
    public function testSaveMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\AbstractVideoProvider::updateMedia
     * @todo   Implement testUpdateMedia().
     */
    public function testUpdateMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\AbstractVideoProvider::removeMedia
     * @todo   Implement testRemoveMedia().
     */
    public function testRemoveMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\AbstractVideoProvider::getMediaUrl
     * @todo   Implement testGetMediaUrl().
     */
    public function testGetMediaUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
