<?php
namespace Kunstmaan\MediaBundle\Tests\Helper\Provider;

use Kunstmaan\MediaBundle\Helper\Provider\ImageProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:31.
 */
class ImageProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ImageProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImageProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\ImageProvider::prepareMedia
     * @todo   Implement testPrepareMedia().
     */
    public function testPrepareMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\ImageProvider::saveMedia
     * @todo   Implement testSaveMedia().
     */
    public function testSaveMedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\ImageProvider::generateFormats
     * @todo   Implement testGenerateFormats().
     */
    public function testGenerateFormats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\ImageProvider::getRenderOptions
     * @todo   Implement testGetRenderOptions().
     */
    public function testGetRenderOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Provider\ImageProvider::setImageManipulator
     * @todo   Implement testSetImageManipulator().
     */
    public function testSetImageManipulator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
