<?php

namespace Kunstmaan\PagePartBundle\Tests\Form;

use Kunstmaan\PagePartBundle\Form\RawHTMLPagePartAdminType;
use Kunstmaan\PagePartBundle\Tests\unit\Form\PagePartAdminTypeTestCase;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-20 at 13:02:14.
 */
class RawHTMLPagePartAdminTypeTest extends PagePartAdminTypeTestCase
{
    /**
     * @var RawHTMLPagePartAdminType
     */
    protected $object;

    protected function setUp(): void
    {
        parent::setUp();
        $this->object = new RawHTMLPagePartAdminType();
    }

    public function testBuildForm()
    {
        $builder = $this->createMock(FormBuilderInterface::class);
        $builder->expects($this->once())->method('add');

        $this->object->buildForm($builder, array());
    }

    public function testConfigureOptions()
    {
        $this->object->configureOptions($this->resolver);
        $resolve = $this->resolver->resolve();
        $this->assertEquals('Kunstmaan\PagePartBundle\Entity\RawHTMLPagePart', $resolve['data_class']);
    }
}
