<?php

namespace Kunstmaan\LeadGenerationBundle\Tests\Entity\Rule;

use Kunstmaan\LeadGenerationBundle\Entity\Rule\AfterXSecondsRule;
use Kunstmaan\LeadGenerationBundle\Form\Rule\AfterXSecondsAdminType;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-04 at 16:54:04.
 */
class AfterXSecondsRuleTest extends PHPUnit_Framework_TestCase
{
    public function testGettersAndSetters()
    {
        $rule = new AfterXSecondsRule();
        $rule->setSeconds(10);

        $this->assertEquals(10, $rule->getSeconds());
        $this->assertEquals('AfterXSecondsRule', $rule->getJsObjectClass());
        $this->assertEquals('/bundles/kunstmaanleadgeneration/js/rule/AfterXSecondsRule.js', $rule->getJsFilePath());
        $this->assertEquals(AfterXSecondsAdminType::class, $rule->getAdminType());
        $this->assertTrue(is_array($rule->getJsProperties()));
    }
}
