liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: uploads/cache
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public"
                    # If you are working with a capistrano like setup you need the following line
                    # - "%kernel.project_dir%/../../shared/public"

    twig:
        mode: lazy

    driver: imagick
    data_loader: default
    filter_sets:
        optim:
            quality: 85
            format: jpg
            filters:
                strip: ~
        optimjpg:
            quality: 85
            format: jpg
            filters:
                strip: ~
        optimpng:
            quality: 85
            format: png
            filters:
                strip: ~

        # ImagePagePart srcset JPG filters
        image_huge_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [2400,null], mode: outbound, allow_upscale: false }
        image_big_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [1200,null], mode: outbound, allow_upscale: false }
        image_medium_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [600,null], mode: outbound, allow_upscale: false }
        image_small_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [400,null], mode: outbound, allow_upscale: false }

        # ImagePagePart srcset PNG filters
        image_huge_png:
            quality: 95
            format: png
            filters:
                strip: ~
                thumbnail: { size: [2400,null], mode: outbound, allow_upscale: false }
        image_big_png:
            quality: 95
            format: png
            filters:
                strip: ~
                thumbnail: { size: [1200,null], mode: outbound, allow_upscale: false }
        image_medium_png:
            quality: 95
            format: png
            filters:
                strip: ~
                thumbnail: { size: [600,null], mode: outbound, allow_upscale: false }
        image_small_png:
            quality: 95
            format: png
            filters:
                strip: ~
                thumbnail: { size: [400,null], mode: outbound, allow_upscale: false }
