services:
    Kunstmaan\MediaBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\MediaBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
