kunstmaan_media:
    cropping_views:
        default:
            - { name: desktop, width: 1, height: 1, lockRatio: false}
            - { name: tablet, width: 1, height: 1, lockRatio: false}
            - { name: phone, width: 1, height: 1, lockRatio: false}
        custom_views:
            example1:
                views:
                    - { name: desktop, width: 50, height: 50, lockRatio: true}
            example2:
                views:
                    - { name: desktop, width: 400, height: 400}
                    - { name: phone, width: 30, height: 30}
