services:
    Kunstmaan\TranslatorBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\TranslatorBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
