<?php

namespace Kunstmaan\SeoBundle\Tests\Entity;

use Kunstmaan\SeoBundle\Twig\SeoTwigExtension;
use Kunstmaan\SeoBundle\Entity\Seo;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-18 at 12:21:52.
 */
class TwigExtensionTests extends \PHPUnit_Framework_TestCase
{
    protected $emMock;
    protected $entityMock;
    protected $seoRepoMock;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->emMock = $this->getMock('\Doctrine\ORM\EntityManager',
            array('getRepository', 'getClassMetadata', 'persist', 'flush'), array(), '', false);
    }

    public function testShouldReturnNameForEntityWhenNoSEO()
    {
        $name = 'OK';

        $this->EntityWithName($name);
        $this->NoSeoFound();

        $object = new SeoTwigExtension($this->emMock);


        $result = $object->getTitleFor($this->entityMock);


        $this->assertEquals($name, $result);
    }


    public function testShouldReturnNameForEntityWhenSEOWithTitleFound()
    {
        $nokName = 'NOK';
        $name = 'OK';

        $this->EntityWithName($nokName);
        $this->SeoFoundWithTitle($name);

        $object = new SeoTwigExtension($this->emMock);


        $result = $object->getTitleFor($this->entityMock);


        $this->assertEquals($name, $result);
    }






    protected function EntityWithName($name)
    {
        $this->entityMock = $this->getMock('Kunstmaan\NodeBundle\Entity\AbstractPage');
        $this->entityMock->expects($this->once())->method('getTitle')->will($this->returnValue($name));
    }

    protected function NoSeoFound()
    {
        $this->ensureSeoRepoMock();
        $this->seoRepoMock->expects($this->once())
            ->method('findFor')
            ->will($this->returnValue(null));

        $this->wireUpSeoRepo();
    }

    protected function ensureSeoRepoMock()
    {
        if (is_null($this->seoRepoMock)) {
            $this->seoRepoMock = $this->getMock('Kunstmaan\SeoBundle\Repository\SeoRepository', [], [], '', false);
        }
    }

    protected function wireUpSeoRepo()
    {
        $this->emMock->expects($this->once())
            ->method('getRepository')
            ->with($this->equalTo('KunstmaanSeoBundle:Seo'))
            ->will($this->returnValue($this->seoRepoMock));
    }

    protected function SeoFoundWithTitle($title)
    {
        $this->ensureSeoRepoMock();

        $seoMock = new Seo();
        $seoMock->setRef($this->entityMock);
        $seoMock->setMetaTitle($title);

        $this->seoRepoMock->expects($this->once())
            ->method('findFor')
            ->will($this->returnValue($seoMock));

        $this->wireUpSeoRepo();
    }

}
