{% if isV4 %}
kunstmaan_page_part:
    pageparts:
        section4:
{% endif %}
{% if isV4 %}            {%endif%}name: "Section 4"
{% if isV4 %}            {%endif%}context: "section4"
{% if isV4 %}            {%endif%}extends: "main"
{% if isV4 %}            {%endif%}types:
{% if isV4 %}            {%endif%}    - { name: "Usp", class: "{{ namespace|replace({'\\': '\\\\'}) }}\\Entity\\PageParts\\UspPagePart" }
