{% if isV4 %}
kunstmaan_page_part:
    pageparts:
        section1:
{% endif %}
{% if isV4 %}            {%endif%}name: "Section 1"
{% if isV4 %}            {%endif%}context: "section1"
{% if isV4 %}            {%endif%}extends: "main"
