{% if isV4 %}
kunstmaan_page_part:
    pageparts:
        section5:
{% endif %}
{% if isV4 %}            {%endif%}name: "Section 5"
{% if isV4 %}            {%endif%}context: "section5"
{% if isV4 %}            {%endif%}extends: "main"
