<?php
namespace Kunstmaan\MediaBundle\Tests\Helper\Generator;

use Kunstmaan\MediaBundle\Helper\Generator\DefaultUuidGenerator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:31.
 */
class DefaultUuidGeneratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DefaultUuidGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DefaultUuidGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\MediaBundle\Helper\Generator\DefaultUuidGenerator::generateUuid
     * @todo   Implement testGenerateUuid().
     */
    public function testGenerateUuid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
