kunstmaanmenubundle_menu_admin_list:
    resource: '@KunstmaanMenuBundle/Controller/MenuAdminListController.php'
    type:     annotation
    prefix:   /admin/menu/

kunstmaanmenubundle_menuitem_admin_list:
    resource: '@KunstmaanMenuBundle/Controller/MenuItemAdminListController.php'
    type:     annotation
    prefix:   /admin/menu/
