<?php

namespace Kunstmaan\SearchBundle\Repository;

use Doctrine\ORM\EntityManager;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use Doctrine\ORM\EntityRepository;

/**
 * SearchedForRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchedForRepository extends EntityRepository
{

}