<?php

namespace Kunstmaan\AdminNodeBundle\Tests\Helper\Menu;

use Kunstmaan\AdminNodeBundle\Helper\Menu\ActionsMenuBuilder;
use Kunstmaan\AdminNodeBundle\Tests\Stubs\TestRepository;
use Knp\Menu\Silex\RouterAwareFactory;
use Kunstmaan\AdminNodeBundle\Entity\NodeTranslation;
use Kunstmaan\AdminNodeBundle\Entity\NodeVersion;
use Doctrine\ORM\EntityManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-23 at 10:49:47.
 */
class ActionsMenuBuilderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ActionsMenuBuilder
     */
    protected $builder;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @covers Kunstmaan\AdminNodeBundle\Helper\Menu\ActionsMenuBuilder::__construct
     */
    protected function setUp()
    {
        $factory = new RouterAwareFactory($this->getMock('Symfony\Component\Routing\Generator\UrlGeneratorInterface'));
        $em = $this->getMockedEntityManager();
        $dispatcher = $this->getMock('Symfony\Component\EventDispatcher\EventDispatcherInterface');
        $router = $this->getMock('Symfony\Component\Routing\RouterInterface');
        $context = $this->getMock('Symfony\Component\Security\Core\SecurityContextInterface');
        $context->expects($this->any())
            ->method('isGranted')
            ->will($this->returnValue(true));

        $this->builder = new ActionsMenuBuilder($factory, $em, $router, $dispatcher, $context);
    }

    /**
     * https://gist.github.com/1331789
     *
     * @return \Doctrine\ORM\EntityManager
     */
    protected function getMockedEntityManager()
    {
        $emMock  = $this->getMock('\Doctrine\ORM\EntityManager', array('getRepository', 'getClassMetadata', 'persist', 'flush'), array(), '', false);
        $emMock->expects($this->any())
            ->method('getRepository')
            ->will($this->returnValue(new TestRepository()));
        $emMock->expects($this->any())
            ->method('getClassMetadata')
            ->will($this->returnValue((object) array('name' => 'aClass')));
        $emMock->expects($this->any())
            ->method('persist')
            ->will($this->returnValue(null));
        $emMock->expects($this->any())
            ->method('flush')
            ->will($this->returnValue(null));

        return $emMock;  // it tooks 13 lines to achieve mock!
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\AdminNodeBundle\Helper\Menu\ActionsMenuBuilder::createSubActionsMenu
     */
    public function testCreateSubActionsMenu()
    {
        $nodeVersion = new NodeVersion();
        $nodeTranslation = new NodeTranslation();
        $nodeVersion->setNodeTranslation($nodeTranslation);
        $this->builder->setActiveNodeVersion($nodeVersion);

        $menu = $this->builder->createSubActionsMenu();
        $this->assertNotNull($menu->getChild('subaction.versions'));

        $this->assertEquals($menu->getChildrenAttribute('class'), 'sub_actions');
    }

    /**
     * @covers Kunstmaan\AdminNodeBundle\Helper\Menu\ActionsMenuBuilder::createActionsMenu
     */
    public function testCreateActionsMenu()
    {
        $nodeVersion = new NodeVersion();
        $nodeTranslation = new NodeTranslation();
        $nodeVersion->setNodeTranslation($nodeTranslation);
        $this->builder->setActiveNodeVersion($nodeVersion);

        $nodeVersion->setType('draft');
        $menu = $this->builder->createActionsMenu();
        $this->assertNotNull($menu->getChild('action.saveasdraft'));
        $this->assertNotNull($menu->getChild('action.publish'));
        $this->assertNotNull($menu->getChild('action.preview'));
        $this->assertNull($menu->getChild('action.save'));
        $this->assertNotNull($menu->getChild('action.delete'));

        $nodeVersion->setType('public');
        $nodeTranslation->setOnline(false);
        $menu = $this->builder->createActionsMenu();
        $this->assertNotNull($menu->getChild('action.save'));
        $this->assertNotNull($menu->getChild('action.saveasdraft'));
        $this->assertNotNull($menu->getChild('action.preview'));
        $this->assertNotNull($menu->getChild('action.publish'));
        $this->assertNull($menu->getChild('action.unpublish'));
        $this->assertNotNull($menu->getChild('action.delete'));

        $nodeVersion->setType('public');
        $nodeTranslation->setOnline(true);
        $menu = $this->builder->createActionsMenu();
        $this->assertNotNull($menu->getChild('action.save'));
        $this->assertNotNull($menu->getChild('action.saveasdraft'));
        $this->assertNotNull($menu->getChild('action.preview'));
        $this->assertNull($menu->getChild('action.publish'));
        $this->assertNotNull($menu->getChild('action.unpublish'));
        $this->assertNotNull($menu->getChild('action.delete'));

        $this->assertEquals($menu->getChildrenAttribute('class'), 'main_actions');
    }

    /**
     * @covers Kunstmaan\AdminNodeBundle\Helper\Menu\ActionsMenuBuilder::createTopActionsMenu
     */
    public function testCreateTopActionsMenu()
    {
        $nodeVersion = new NodeVersion();
        $nodeTranslation = new NodeTranslation();
        $nodeVersion->setNodeTranslation($nodeTranslation);
        $this->builder->setActiveNodeVersion($nodeVersion);

        $menu = $this->builder->createTopActionsMenu();
        $this->assertEquals($menu->getChildrenAttribute('class'), 'main_actions top');
        $this->assertEquals($menu->getChildrenAttribute('id'), 'main_actions_top');
    }

    /**
     * @covers Kunstmaan\AdminNodeBundle\Helper\Menu\ActionsMenuBuilder::setActiveNodeVersion
     * @covers Kunstmaan\AdminNodeBundle\Helper\Menu\ActionsMenuBuilder::getActiveNodeVersion
     */
    public function testSetGetActiveNodeVersion()
    {
        $nodeVersion = new NodeVersion();
        $this->builder->setActiveNodeVersion($nodeVersion);
        $this->assertEquals($this->builder->getActiveNodeVersion(), $nodeVersion);
    }

}
