{% if isV4 %}
kunstmaan_page_part:
    pagetemplates:
        formpage:
{%endif%}
{% if isV4 %}            {%endif%}name: "Form page"
{% if isV4 %}            {%endif%}rows:
{% if isV4 %}            {%endif%}    - regions:
{% if isV4 %}            {%endif%}        - { name: "main", span: 12 }
{% if isV4 %}            {%endif%}template: "{% if not isV4 %}{{ bundle.name }}::{% endif %}Pages\\FormPage\\pagetemplate.html.twig"
