services:
    Kunstmaan\GeneratorBundle\Maker\MakeWebsiteSkeleton:
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: maker.command }

    Kunstmaan\GeneratorBundle\Maker\MakeDefaultPageparts:
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: maker.command }

