<?php

namespace Kunstmaan\AdminBundle\Tests\Entity;

use Kunstmaan\AdminBundle\Entity\LogItem;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-04 at 16:53:10.
 */
class LogItemTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LogItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LogItem();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::getId
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::setId
     */
    public function testGetSetId()
    {
        $this->object->setId(2);
        $this->assertEquals(2, $this->object->getId());
    }

    /**
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::getStatus
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::setStatus
     */
    public function testGetSetStatus()
    {
        $this->object->setStatus('status');
        $this->assertEquals('status', $this->object->getStatus());
    }

    /**
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::getUser
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::setUser
     */
    public function testGetSetUser()
    {
        $user = $this->getMock('Kunstmaan\AdminBundle\Entity\User');
        $this->object->setUser($user);
        $this->assertEquals($user, $this->object->getUser());
    }

    /**
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::getMessage
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::setMessage
     */
    public function testGetSetMessage()
    {
        $this->object->setMessage('A simple test message');
        $this->assertEquals('A simple test message', $this->object->getMessage());
    }

    /**
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::getCreatedAt
     * @covers Kunstmaan\AdminBundle\Entity\LogItem::setCreatedAt
     */
    public function testGetSetCreatedAt()
    {
        $dateTime = new \DateTime();
        $this->object->setCreatedAt($dateTime);
        $this->assertEquals($dateTime, $this->object->getCreatedAt());
    }

}
