<?php
namespace Kunstmaan\MediaBundle\Tests\AdminList;

use Kunstmaan\AdminListBundle\AdminList\AdminListFilter;

use Kunstmaan\MediaBundle\Entity\Folder;

use Kunstmaan\MediaBundle\AdminList\MediaListConfigurator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 16:16:29.
 */
class MediaListConfiguratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MediaListConfigurator
     */
    protected $object;

    /**
     * @var Folder
     */
    protected $folder;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->folder = new Folder();
        $this->folder->setId(5);
        $this->object = new MediaListConfigurator($this->folder);
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::buildFilters
     * @todo   Implement testBuildFilters().
     */
    public function testBuildFilters()
    {
        $adminListFilter = new AdminListFilter();
        $this->object->buildFilters($adminListFilter);
        $this->assertTrue($adminListFilter->has('name'));
        $this->assertTrue($adminListFilter->has('classtype'));
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::buildFields
     * @todo   Implement testBuildFields().
     */
    public function testBuildFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::canAdd
     */
    public function testCanAdd()
    {
        $this->assertFalse($this->object->canAdd());
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::getAddUrlFor
     * @todo   Implement testGetAddUrlFor().
     */
    public function testGetAddUrlFor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::getEditUrlFor
     * @todo   Implement testGetEditUrlFor().
     */
    public function testGetEditUrlFor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::getIndexUrlFor
     * @todo   Implement testGetIndexUrlFor().
     */
    public function testGetIndexUrlFor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::getRepositoryName
     * @todo   Implement testGetRepositoryName().
     */
    public function testGetRepositoryName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::adaptQueryBuilder
     * @todo   Implement testAdaptQueryBuilder().
     */
    public function testAdaptQueryBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kunstmaan\MediaBundle\AdminList\MediaListConfigurator::getDeleteUrlFor
     * @todo   Implement testGetDeleteUrlFor().
     */
    public function testGetDeleteUrlFor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
