<?php

namespace Kunstmaan\FormBundle\Tests\Entity\PageParts;

use Kunstmaan\FormBundle\Entity\PageParts\AbstractFormPagePart;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-21 at 09:48:21.
 */
class AbstractFormPagePartTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractFormPagePart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass("Kunstmaan\FormBundle\Entity\PageParts\AbstractFormPagePart");
    }

    public function testGetUniqueId()
    {
        $object = $this->object;
        $object->getUniqueId();
    }

    public function testSetGetLabel()
    {
        $object = $this->object;
        $value = 'Some label';
        $object->setLabel($value);
        $this->assertEquals($value, $object->getLabel());
    }

    public function testGetAdminView()
    {
        $stringValue = $this->object->getAdminView();
        $this->assertNotNull($stringValue);
        $this->assertTrue(is_string($stringValue));
    }
}
