services:
    Kunstmaan\NodeSearchBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Resources,Tests,Controller,Features,Helper}'

    Kunstmaan\NodeSearchBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        public: true
