parameters:
    kunstmaan_node_search.search_configuration.number_of_shards: 1
    kunstmaan_node_search.search_configuration.number_of_replicas: 0
    kunstmaan_node_search.indexname: 'nodeindex'
    kunstmaan_node_search.indextype: 'page'
    kunstmaan_node_search.search.node.class: Kunstmaan\NodeSearchBundle\Search\NodeSearcher
    kunstmaan_node_search.search_configuration.node.class: Kunstmaan\NodeSearchBundle\Configuration\NodePagesConfiguration
    kunstmaan_node_search.search_service.class: Kunstmaan\NodeSearchBundle\Services\SearchService

services:
    Kunstmaan\NodeSearchBundle\Search\AbstractElasticaSearcher:
        abstract: true
        calls:
            - [ setSearch, ['@Kunstmaan\SearchBundle\Search\Search']]

    Kunstmaan\NodeSearchBundle\Search\NodeSearcher:
        parent: Kunstmaan\NodeSearchBundle\Search\AbstractElasticaSearcher
        calls:
            - [ setIndexName, ['%kunstmaan_node_search.indexname%']]
            - [ setIndexType, ['%kunstmaan_node_search.indextype%']]
            - [ setTokenStorage, ['@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface']]
            - [ setDomainConfiguration, ['@Kunstmaan\AdminBundle\Helper\DomainConfigurationInterface']]
            - [ setEntityManager, ['@Doctrine\ORM\EntityManagerInterface']]

    Kunstmaan\NodeSearchBundle\Helper\IndexablePagePartsService:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '%kunstmaan_node_search.contexts%'

    Kunstmaan\NodeSearchBundle\Twig\KunstmaanNodeSearchTwigExtension:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Kunstmaan\NodeSearchBundle\Helper\IndexablePagePartsService'
        tags:
            - { name: twig.extension }

    Kunstmaan\NodeSearchBundle\Configuration\NodePagesConfiguration:
        arguments:
            - '@Symfony\Component\DependencyInjection\ContainerInterface'
            - '@Kunstmaan\SearchBundle\Search\Search'
            - '%kunstmaan_node_search.indexname%'
            - '%kunstmaan_node_search.indextype%'
            - '%kunstmaan_node_search.search_configuration.number_of_shards%'
            - '%kunstmaan_node_search.search_configuration.number_of_replicas%'
        calls:
            - [ setAclProvider, ['@security.acl.provider']]
            - [ setIndexablePagePartsService, ['@Kunstmaan\NodeSearchBundle\Helper\IndexablePagePartsService']]
        tags:
            - { name: kunstmaan_search.search_configuration, alias: Node }

    Kunstmaan\NodeSearchBundle\Services\SearchService:
        arguments:
            - '@Symfony\Component\DependencyInjection\ContainerInterface'
            - '@Symfony\Component\HttpFoundation\RequestStack'
