<?php

namespace Kunstmaan\PagePartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagePartRefRepository extends EntityRepository
{

    public function addPagePart($page, $pagepart, $sequencenumber, $context = "main"){
        $pagepartref = new \Kunstmaan\PagePartBundle\Entity\PagePartRef();
        $pagepartref->setContext($context);
        $pagepartref->setPageEntityname(get_class($page));
        $pagepartref->setPageId($page->getId());
        $pagepartref->setPagePartEntityname(get_class($pagepart));
        $pagepartref->setPagePartId($pagepart->getId());
        $pagepartref->setSequencenumber($sequencenumber);
        $this->getEntityManager()->persist($pagepartref);
    }
}