<?php

namespace Kunstmaan\PagePartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagePartRefRepository extends EntityRepository
{

    public function addPagePart($page, $pagepart, $sequencenumber, $context = "main"){
        $pagepartref = new \Kunstmaan\PagePartBundle\Entity\PagePartRef();
        $pagepartref->setContext($context);
        $pagepartref->setPageEntityname(get_class($page));
        $pagepartref->setPageId($page->getId());
        $pagepartref->setPagePartEntityname(get_class($pagepart));
        $pagepartref->setPagePartId($pagepart->getId());
        $pagepartref->setSequencenumber($sequencenumber);
        $this->getEntityManager()->persist($pagepartref);
    }
    
    public function getPagePartRefs($em, $page){
    	return $this->findBy(array('pageId' => $page->getId(), 'pageEntityname' => get_class($page)));
    }
    
    public function getPageParts($em, $page){
    	$pagepartrefs = $this->getPagePartRefs($em, $page);
    	$result = array();
    	foreach($pagepartrefs as $pagepartref){
    		$result[] = $pagepartref->getPagePart($em);
    	}
    	return $result;
    }
}