<?php

namespace Kunstmaan\PagePartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagePartRefRepository extends EntityRepository
{

    public function addPagePart($page, $pagepart, $sequencenumber, $context = "main"){
    	$pagepartrefs = $this->getPagePartRefs($page);
    	foreach($pagepartrefs as $pagepartref){
    		if($pagepartref->getSequencenumber()>=$sequencenumber){
    			$pagepartref->setSequencenumber($pagepartref->getSequencenumber()+1);
    			$this->getEntityManager()->persist($pagepartref);
    		}
    	}
        $pagepartref = new \Kunstmaan\PagePartBundle\Entity\PagePartRef();
        $pagepartref->setContext($context);
        $pagepartref->setPageEntityname(get_class($page));
        $pagepartref->setPageId($page->getId());
        $pagepartref->setPagePartEntityname(get_class($pagepart));
        $pagepartref->setPagePartId($pagepart->getId());
        $pagepartref->setSequencenumber($sequencenumber);
        $this->getEntityManager()->persist($pagepartref);
    }
    
    public function getPagePartRefs($page){
    	return $this->findBy(array('pageId' => $page->getId(), 'pageEntityname' => get_class($page)), array('sequencenumber' => 'ASC'));
    }
    
    public function getPageParts($page){
    	$pagepartrefs = $this->getPagePartRefs($page);
    	$result = array();
    	foreach($pagepartrefs as $pagepartref){
    		$result[] = $pagepartref->getPagePart($this->getEntityManager());
    	}
    	return $result;
    }
}