name: Code quality

on:
  [push, pull_request]

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   name: Install Composer Dependencies
                uses: ramsey/composer-install@v1

            -   name: Run phpstan
                run: vendor/bin/phpstan analyse --no-progress
