<?php

namespace Kunstmaan\NodeBundle\Tests\Entity;

use Kunstmaan\NodeBundle\Entity\Node;
use Kunstmaan\NodeBundle\Entity\NodeTranslation;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-14 at 11:09:16.
 */
class NodeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Node
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Node();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::isHiddenFromNav
     * @covers Kunstmaan\NodeBundle\Entity\Node::getHiddenFromNav
     * @covers Kunstmaan\NodeBundle\Entity\Node::setHiddenFromNav
     */
    public function testIsGetSetHiddenFromNav()
    {
        $this->assertFalse($this->object->getHiddenFromNav());
        $this->object->setHiddenFromNav(true);
        $this->assertTrue($this->object->isHiddenFromNav());
        $this->assertTrue($this->object->getHiddenFromNav());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::__construct
     * @covers Kunstmaan\NodeBundle\Entity\Node::getChildren
     * @covers Kunstmaan\NodeBundle\Entity\Node::setChildren
     */
    public function testGetSetChildren()
    {
        $children = new ArrayCollection();
        $child = new Node();
        $children->add($child);
        $this->object->setChildren($children);

        $this->assertEquals(1, $this->object->getChildren()->count());
        $this->assertEquals($children, $this->object->getChildren());
        $this->assertTrue($this->object->getChildren()->contains($child));
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::getChildren
     * @covers Kunstmaan\NodeBundle\Entity\Node::setChildren
     */
    public function testGetSetChildrenWithDeletedChildren()
    {
        $children = new ArrayCollection();
        $child = new Node();
        $deletedChild = new Node();
        $deletedChild->setDeleted(true);
        $children->add($child);
        $children->add($deletedChild);
        $this->object->setChildren($children);

        $this->assertEquals(1, $this->object->getChildren()->count());
        $this->assertTrue($this->object->getChildren()->contains($child));
        $this->assertFalse($this->object->getChildren()->contains($deletedChild));
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::addNode
     * @covers Kunstmaan\NodeBundle\Entity\Node::setParent
     * @covers Kunstmaan\NodeBundle\Entity\Node::getParent
     */
    public function testAddNode()
    {
        $child = new Node();
        $this->object->addNode($child);
        $this->assertEquals($this->object, $child->getParent());
        $this->assertEquals(1, $this->object->getChildren()->count());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::getNodeTranslations
     * @covers Kunstmaan\NodeBundle\Entity\Node::setNodeTranslations
     */
    public function testGetSetNodeTranslations()
    {
        $translations = new ArrayCollection();
        $translation = new NodeTranslation();
        $translations->add($translation);
        $this->object->setNodeTranslations($translations);

        $this->assertEquals(1, $this->object->getNodeTranslations(true)->count());
        $this->assertEquals($translations, $this->object->getNodeTranslations(true));
        $this->assertTrue($this->object->getNodeTranslations(true)->contains($translation));
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::addNodeTranslation
     * @covers Kunstmaan\NodeBundle\Entity\Node::getNodeTranslations
     */
    public function testGetNodeTranslationsWithOfflineNodes()
    {
        $translation1 = new NodeTranslation();
        $translation1->setOnline(true);
        $this->object->addNodeTranslation($translation1);

        $translation2 = new NodeTranslation();
        $translation2->setOnline(false);
        $this->object->addNodeTranslation($translation2);

        $this->assertEquals(2, $this->object->getNodeTranslations(true)->count());
        $this->assertEquals(1, $this->object->getNodeTranslations()->count());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::addNodeTranslation
     * @covers Kunstmaan\NodeBundle\Entity\Node::getNodeTranslation
     */
    public function testGetNodeTranslation()
    {
        $translation1 = new NodeTranslation();
        $translation1->setLang('nl');
        $translation1->setOnline(true);
        $this->object->addNodeTranslation($translation1);

        $translation2 = new NodeTranslation();
        $translation2->setLang('fr');
        $translation2->setOnline(true);
        $this->object->addNodeTranslation($translation2);

        $this->assertEquals($translation1, $this->object->getNodeTranslation('nl'));
        $this->assertEquals($translation2, $this->object->getNodeTranslation('fr'));
        $this->assertNotEquals($translation1, $this->object->getNodeTranslation('fr'));
        $this->assertNotEquals($translation2, $this->object->getNodeTranslation('nl'));
        $this->assertNull($this->object->getNodeTranslation('en'));
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::getParents
     */
    public function testGetParents()
    {
        $child = new Node();
        $grandChild = new Node();
        $child->addNode($grandChild);
        $this->object->addNode($child);
        $parents = $grandChild->getParents();

        $this->assertEquals(2, count($parents));
        $this->assertEquals($child, $parents[1]);
        $this->assertEquals($this->object, $parents[0]);
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::setSequenceNumber
     * @covers Kunstmaan\NodeBundle\Entity\Node::getSequenceNumber
     */
    public function testSetGetSequenceNumber()
    {
        $this->object->setSequenceNumber(1);
        $this->assertEquals(1, $this->object->getSequenceNumber());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::isDeleted
     * @covers Kunstmaan\NodeBundle\Entity\Node::setDeleted
     */
    public function testIsSetDeleted()
    {
        $this->assertFalse($this->object->isDeleted());
        $this->object->setDeleted(true);
        $this->assertTrue($this->object->isDeleted());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::setRef
     * @covers Kunstmaan\NodeBundle\Entity\Node::setRefEntityName
     * @covers Kunstmaan\NodeBundle\Entity\Node::getRefEntityName
     */
    public function testSetRefAndGetRefEntityName()
    {
        $entity = new TestEntity();
        $this->object->setRef($entity);
        $this->assertEquals('Kunstmaan\NodeBundle\Tests\Entity\TestEntity', $this->object->getRefEntityName());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::setInternalName
     * @covers Kunstmaan\NodeBundle\Entity\Node::getInternalName
     */
    public function testSetInternalName()
    {
        $this->object->setInternalName('AnInternalName');
        $this->assertEquals('AnInternalName', $this->object->getInternalName());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::getDefaultAdminType
     */
    public function testGetDefaultAdminType()
    {
        $this->assertInstanceOf('Kunstmaan\NodeBundle\Form\NodeAdminType', $this->object->getDefaultAdminType());
    }

    /**
     * @covers Kunstmaan\NodeBundle\Entity\Node::__toString
     */
    public function testToString()
    {
        $this->object->setId(1);
        $this->object->setRef(new TestEntity());

        $this->assertEquals('node 1, refEntityName: Kunstmaan\NodeBundle\Tests\Entity\TestEntity', $this->object->__toString());
    }
}
